services:
  - type: web
    name: helmet-detection-api
    runtime: python
    buildCommand: pip install -r requirements-railway.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_MODEL_REPO
        value: raghavendra24/helmet-yolov8s
      - key: PYTHON_VERSION
        value: "3.10.12"
    healthCheckPath: /health
